server:
  port: 9001

spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/shop
    url: jdbc:mysql://localhost:3306/shop
    username: shopadmin
    password: admin
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

